config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root 'contacts#index'

end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :phone, type: Integer
  field :address, type: String
  field :_id, type: String, default: ->{ name.to_s.parameterize }

  validates :name, presence: true, uniqueness: true
  validates :phone, presence: true, length: {is: 10}
  
  belongs_to :user

end

app/models/user.rb
class User
  include Mongoid::Document
  field :id, type: Integer
  field :u_name, type: String
  field :password, type: String
  
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= simple_form_for @contact, html: { class: "form form-horizontal contact" } do |f|
  
  = f.input :name
  = f.input :email
  = f.input :phone
  = f.input :address

  .actions
    = f.submit nil,class: 'btn btn-lg btn-info'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), contacts_path, :class => 'btn btn-lg btn-danger'

app/views/contacts/edit.html.haml
- model_class = Contact
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
  = link_to contacts_path, :class => 'back' do
    = fa_icon "arrow-circle-left"
    Back
.row.contacts-edit
  = render :partial => "form"

app/views/contacts/index.html.haml
- model_class = Contact
.page-header.row
  %h1.title
    = 'Contact.ly'
  %span A basic rails contact app
.row.contacts-index
  - if @contacts.empty?
    .row.no-contacts
      %h2 Whoops, please add some contacts
      %p You can add contacts by pressing the button below.
  - else
    - @contacts.each do |contact|
      .col-md-6.col-lg-4.contact
        = link_to(contact_path(contact)) do
          .contact-header
            %h3.name= contact.name
          .contact-body
            .email.detail
              = fa_icon "circle"
              %span= contact.email
            .phone.detail
              = fa_icon "circle"
              %span= contact.phone
        .actions
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_path(contact), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), contact_path(contact), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

.row
  = link_to new_contact_path, :class => 'btn btn-info new-contact' do
    = fa_icon "plus"
    New Contact

app/views/contacts/new.html.haml
- model_class = Contact
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
  = link_to contacts_path, :class => 'back' do
    = fa_icon "arrow-circle-left"
    Back
.row.contacts-new
  = render :partial => "form"

app/views/contacts/show.html.haml
- model_class = Contact
.page-header
  = link_to contacts_path, :class => 'back' do
    = fa_icon "arrow-circle-left"
    Back
  %h1= @contact.name
  = link_to edit_contact_path(@contact), :class => 'edit' do
    = fa_icon "pencil-square"
    Edit
.row.contact-show
  %p.email
    = fa_icon "circle"
    %span= @contact.email
  %p.phone
    = fa_icon "circle"
    %span= @contact.phone
  %p.address
    = fa_icon "circle"
    %span= @contact.address

  = link_to t('.destroy', :default => t("helpers.links.destroy")), contact_path(@contact), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-lg btn-danger'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Contact.ly | A rails contact app
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
  .container-fluid

    = bootstrap_flash(id: "alert")

    = yield